from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 384)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 40, 471, 301))
        self.widget.setStyleSheet("background-color:rgba(0, 205, 0, 0.9);\n"
"border-radius: 10px")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(170, 40, 131, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgba(255, 255, 255, 1);\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 60, 91, 16))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(40, 110, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.new_username_input = QtWidgets.QLineEdit(parent=self.widget)
        self.new_username_input.setGeometry(QtCore.QRect(290, 70, 113, 20))
        self.new_username_input.setStyleSheet("background-color:white;")
        self.new_username_input.setObjectName("new_username_input")
        self.new_password_input = QtWidgets.QLineEdit(parent=self.widget)
        self.new_password_input.setGeometry(QtCore.QRect(290, 110, 113, 20))
        self.new_password_input.setStyleSheet("background-color:white;")
        self.new_password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.new_password_input.setObjectName("new_password_input")
        self.register_button = QtWidgets.QPushButton(parent=self.widget)
        self.register_button.setGeometry(QtCore.QRect(170, 220, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.register_button.setFont(font)
        self.register_button.setStyleSheet("background-color:white;")
        self.register_button.setObjectName("register_button")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setObjectName("label_5")
        self.confirm_password_input = QtWidgets.QLineEdit(parent=self.widget)
        self.confirm_password_input.setGeometry(QtCore.QRect(290, 150, 113, 20))
        self.confirm_password_input.setStyleSheet("background-color:white;")
        self.confirm_password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirm_password_input.setObjectName("confirm_password_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Đăng Ký"))
        self.label_2.setText(_translate("MainWindow", "HÃY TẠO TÀI KHOẢN"))
        self.label_3.setText(_translate("MainWindow", "NHẬP TÊN NGƯỜI DÙNG:"))
        self.label_4.setText(_translate("MainWindow", "NHẬP MẬT KHẨU MỚI CHO TÀI KHOẢN:"))
        self.register_button.setText(_translate("MainWindow", "HOÀN TẤT"))
        self.label_5.setText(_translate("MainWindow", "XÁC NHẬN MẬT KHẨU:"))
